name: issue validator
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run fabiankoestring/body-regex-validator-action
        uses: fabiankoestring/body-regex-validator-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_PATTERN: '^(.*Description.*Changes.*Tests.*)$'
          PULL_REQUEST_COMMENT: 'This is my pr comment template.'
          ISSUE_PATTERN: '^(.*\[plugin_bambu_printer_serial\.log\].*)|(.*\[octoprint\.log\].*)$'
          ISSUE_COMMENT: 'This is my issue comment template.'
