name: issue validator
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Validator
        uses: jneilliii/body-regex-validator-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_PATTERN: '^(.*Description.*Changes.*Tests.*)$'
          PULL_REQUEST_COMMENT: 'This is my pr comment template.'
          ISSUE_PATTERN: '^(.*\[plugin_bambu_printer_serial\.log\].*\[octoprint\.log\].*)|(.*\[octoprint\.log\].*\[plugin_bambu_printer_serial\.log\].*)$'
          ISSUE_COMMENT: 'Required log files not included, please edit original post with octoprint.log and plugin_bambu_printer_serial.log.'
